version: '3'
services:
  web:
    image: nginx:latest
    restart: always
    volumes:    
    - ./html:/usr/share/nginx/html:ro
    ports:
    - 80:80

  ops:
    image: jenkins/jenkins:latest 
    restart: always
    ports:
    - 8080:8080
    - 5000:5000
