apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-jenkins
  name: nginx-jenkins-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-jenkins
  template:
    metadata:
      labels:
        app: nginx-jenkins
    spec:
      containers:
        - name: nginx-jenkins
          image: 10.2.123.55:5555/root/nginx-jenkins:BUILD_ID
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab-reg-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-jenkins
  name: nginx-jenkins-service
spec:
  selector:
     app: nginx-jenkins
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
